### ISSUE TITLE
Undersök och åtgärda avvikelser i gränssnittet jfrt med specen på https://alternativ.nu/skiss190315.pdf

### ISSUE THREAD

**Issue by recraft-ou** [alternativ-nu/retrosearch#1]
- Högerspalt?
- Gruppera artiklarna per nr så bara en framsida, tillgänglighetsmarkör och köpknapp visas per nr?
- Går ämnesorden i filtreringen att gruppera så underkategorier bara visas för vald överkategori?
- Filterering visar endast ett ämne i taget?
- Visa alla artiklar istf sidor, eller blir det för långsamt? Alt, autoladdning av nya vid scrollning.
- Bara visa ingress (+ ingressbild) vid klickning/hovring?

**Comment by recraft-ou** [comment]
Ett utkast finns nu på https://retrosearch.recraft.me med artiklar grupperade per nr och köpknapp.

Paging är borttaget. Det blir då en scrollbar på https://retrosearch.recraft.me/artiklar/ men man ser alla poster på samma sida.

**Comment by TidningenAter** [comment]
Jag har tagit upp flera av ovanstående som egna issues, känns mer lätthanterligt att kunna diskutera var sak för sig. Så om du inte misstycker kan vi skrota denna tråd.
