### ISSUE TITLE
Saknade framsidebilder

### ISSUE THREAD

**Issue by TidningenAter** [alternativ-nu/retrosearch#10]
Det finns en mapp med bilder i dropboxmappen: https://www.dropbox.com/sh/lgubx62a619p79d/AAARVRSMU1_wR9yg2lPq47CIa?dl=0
Nu är filerna bara döpta efter år o nr men jag kan exportera annorlunda och i annan storlek/format om du vill.

**Comment by recraft-ou** [comment]
Just nu används bilderna från butiken, men att ta detta från dropboxmappen skulle kunna göra det hela lite snabbare så det kunde ju vara en god idé.

**Comment by TidningenAter** [comment]
Såg att det på vissa tidningar även saknas titeln

**Comment by recraft-ou** [comment]
Oj då, kommer du ihåg vilka? 

Jag försökte nu kolla mot datan som ska komma från någon av .tab-filerna (den med artiklar), men där hittar jag ingen tom "title", så jag kanske har gjort något misstag när detta formatteras för att visas i tabellen.

**Comment by recraft-ou** [comment]
Aha, där titeln saknas så var det inte titeln på artikeln utan på tidningsnr och det verkar sammanfalla med de som saknar bild som ju denna ticket handlar om, jag ser nu detta och kan jobba på att fixa till detta på egen hand.

**Comment by TidningenAter** [comment]
Ja, det var tidningstiteln jag menade. Och det verkar vara som du säger att den inte syns när framsidan saknas.

Finns ett par andra fel, som kanske är relaterade: 2/10 visas dubbelt och 2/04 är uppdelad i två. 
Kanske är det något fel i min tabfil?
<img width="562" alt="Skärmklipp 2019-08-06 21 01 21" src="https://user-images.githubusercontent.com/49936253/62568506-a5055380-b88d-11e9-868d-57c2d50b86ae.png">
<img width="508" alt="Skärmklipp 2019-08-06 20 59 42" src="https://user-images.githubusercontent.com/49936253/62568507-a5055380-b88d-11e9-8631-8ee8a54b3673.png">

**Comment by recraft-ou** [comment]
Jag provar lokalt (ej deployat) att använda bilderna från dropbox-exporten på https://www.dropbox.com/sh/lgubx62a619p79d/AAARVRSMU1_wR9yg2lPq47CIa?raw=1 och cachear bilderna däri så appen inte hämtar bilderna externt från butiken.

Det ser ut som att det saknas bilder för tre nr: nr 2 och 3 från 2019 och nr 2 från 2018 i dropbox-exporten. Det vore fint att få med dessa också däri.

**Comment by recraft-ou** [comment]
Det andra felet du hittade (med dubbling och uppdelning) verkar iaf i ett fall vara kopplat till att jag missar att beakta "active" flaggan i datan från PS API:et som är 0 för de två produkter för Åter 2/10 som API:et rapporterar , jag ska kolla upp det andra fallet fixa detta när jag utrett denna bugg.

**Comment by TidningenAter** [comment]
Ja, det fanns två 2/10, en med ändelsen -restex men jag har tagit bort den nu. Det finns en massa andra slutsålda nr med samma ändelse, ska jag radera eller döpa om dem? Artikelnumret i butiken för de olika numren är dess namn utan /.   Dvs 3/09 har 309. Men frågan är om det är bra att hämta så mycket saker från PS istället för filerna jag laddar upp, infon finns ju även där. 

/Petter

**Comment by TidningenAter** [comment]
De ska finnas där nu. Är formatet på namnet bra, eller ska jag lägga till ändelsen .jpg etc?

**Comment by recraft-ou** [comment]
Finemang! Visst vore det behändigt med .jpg-ändelse.

**Comment by recraft-ou** [comment]
Att hämta från PS ger lite mer up-to-date info, eftersom den andra infon kommer in nattligen. För bilderna får man utgå från att de sällan förändras förutom när ett nytt nr släpps. Det kan vara bra att hämta exv availability-data från PS för det är bra att man ser direkt ifall en produkt tar slut, men annars försöker jag sikta primärt på att ta data från dump-filerna.

**Comment by TidningenAter** [comment]
OK, fast som jag tror jag nämnde så är lagersaldot i PS inte alls korrekt. När en tidning tar slut här kan det finnas hundratals kvar enligt PS, så då går jag in och avaktiverar produkten manuellt.

**Comment by recraft-ou** [comment]
Nu tror jag att de flesta bilderna är där förutom 2018 för nr 2, som verkade saknas i dropbox-exporten, kan det stämma?

**Comment by TidningenAter** [comment]
Ah, det stämmer. Har fixat det nu. Såg även att jag missat lägga till ändelsen .jpg på alla. Fixar det.

**Comment by recraft-ou** [comment]
Nu har den kommit upp (på https://alternativ.nu/artiklar), om du är nöjd kan vi stänga denna?

**Comment by TidningenAter** [comment]
Perfekt : )
