### ISSUE TITLE
Visa Alla i tillgänglighetsfiltreringen

### ISSUE THREAD

**Issue by TidningenAter** [alternativ-nu/retrosearch#12]
Nu finns de 4 valen Slut, Tryckt, Köpt via prenumeration, samt Ej köpt i lager.
Det vore kanske bra med valet "Visa alla"?

Inte viktigt men kanske man skulle ha att de två sista bara visas om man inte angett prenumerantnummer. "Köpt via prenumeration" kan bara heta "Köpt"

Vilket av valen är default nu?

**Comment by recraft-ou** [comment]
Bra förslag med lite bättre benämningar, som är lättare att förstå. Kanske vill man visa alla som förval och sedan om man angett pnr så markeras i listan vilka man har köpt och vilka man kan köpa eftersom de finns i lager, så man kan komplettera sin samling. De som är slut kan få någon markering också? Snarare än ett dropdown filter kunde det vara en egen kolumn ned symboler som anger tillgängligheten kanske?

**Comment by TidningenAter** [comment]
Ja, det är bra med symboler, men för att det inte ska bli dubbla symboler om man t e x äger ett nr som är slutsålt, så räcker det kanske med en symbol för om man köpt tidningen. Sedan visar köpknappen huruvida den finns i lager eller ej.

**Comment by TidningenAter** [comment]
Visa alla
I lager
Slutsålda
Köpt
Ej köpta, i lager

**Comment by recraft-ou** [comment]
Finns nu en nu version på alternativ.nu/artiklar

**Comment by TidningenAter** [comment]
Det står fortfarande "Tryckt" istället för "I lager"

**Comment by recraft-ou** [comment]
Nu har de värden som exporteras blivit omkodade från "Tryckt" till "I lager".

**Comment by TidningenAter** [comment]
Jag förstår nu att det måste komma från min exportfil, jag fixar det.

**Comment by recraft-ou** [comment]
Inga problem, jag översätter det på mottagarsidan just nu ifall det förekommer sådana värden. Men om du ändrar i exporten så bör inte det påverka något, så gör det om du har möjlighet, men ingen brådska.

**Comment by recraft-ou** [comment]
Om du är nöjd med hur det här ser ut och funkar för tillfället så kan vi stänga denna issue?

**Comment by TidningenAter** [comment]
Japp, vi stänger.
