### ISSUE TITLE
Hämta prenumerantnumret via Prestashop?

### ISSUE THREAD

**Issue by TidningenAter** [alternativ-nu/retrosearch#15]
Vet inte om det är en bra idé, men vill ändå påpeka möjligheten. Det fanns två fält för telefonnummer i Prestashop och det ena använder jag för prenumerantnummer. Eftersom PS har långa cookies så är många redan inloggade och kan kunde prenumerantnumret automatiskt hämta det i de fall folk fyllt i det, eller rent av använda själva fältet. 
Det är dock långt från alla som fyllt i det och det är inget jag fyllt i efterhand så nya kunder har tomma fält. Jag har iofs Prestashopkundnumren också i Filemaker så jag kan koppla ihop dem med ett visst prenumerantnummer. 
Men det är nog bara krångligt och kanske är det bäst man själv fyller i det manuellt. Men jag ville ändå nämna saken i fall du kan se någon nytta med det.

**Comment by recraft-ou** [comment]
Bra att veta. Nu används pnr från dumpfilen där min tanke är att först köra en nattlig uppdatering, men går man via API:et skulle man kanske kunna hämta hela tiden.

**Comment by TidningenAter** [comment]
Det där hängde jag inte med på. 
Många är inte alls inloggade i butiken, eller ens har angett sin p-nr där.

**Comment by TidningenAter** [comment]
Jag tycker vi skippar och stänger detta?
