### ISSUE TITLE
Redan köpta nummer - felaktig data

### ISSUE THREAD

**Issue by recraft-ou** [alternativ-nu/retrosearch#18]
Kolla att tillgängligheten köp via prenumeration funkar - testa för ett antal pnr....

Är det någon konstig indata för potterna?

**Comment by TidningenAter** [comment]
Hej
1. Har testat nu och tillgänglighetsfiltreringen funkar fortfarande inte. Det dyker alltså upp nummer som man köpt eller inte köpt, som är slut eller inte slut, oberoende av vad man väljer. Jag bifogar 4 poster ur registret du kan testa med för jag förstår att det inte är så lätt att se utifrån tab-filen. 
I denna ”portal” i mitt register så visas inte nummer som är slutsålda, såvida personen inte köpt dem. Om de är oköpta och finns i lager så visas en grön köp-knapp.

2. Ang de konstiga värdena i pott-filen så ser jag bara att den sista med P är felaktig, vilket är fixat nu. De som har tomma credits kan jag byta ut till 0 och de med decimaler kan jag avrunda om du vill. Men jag förstår inte vad tredje spalten ”n” är?

3. Såg Återkopplingslänken, den var snygg men du kan justera länken så det inte öppnas ett nytt fönster i webbläsaren och ta bort // efter mailto:

4. Jag exporterar nya tab-filer i morgon. Är det OK och är det något jag ska tänka på?

P.S. Tidningen skickades i fredags och bör då vara i lådorna på onsdag.

/Petter

**Comment by TidningenAter** [comment]
Har testat nu och tillgänglighetsfiltreringen funkar fortfarande inte. Det dyker alltså upp nummer som man köpt eller inte köpt, som är slut eller inte slut, oberoende av vad man väljer. Jag bifogar 4 poster ur registret du kan testa med för jag förstår att det inte är så lätt att se utifrån tab-filen. 
I denna ”portal” i mitt register så visas inte nummer som är slutsålda, såvida personen inte köpt dem. Om de är oköpta och finns i lager så visas en grön köp-knapp.

<img width="135" alt="Skärmklipp 2019-08-05 14 29 49" src="https://user-images.githubusercontent.com/49936253/62465956-75bcec80-b790-11e9-90ea-28c23091500c.png"> <img width="133" alt="Skärmklipp 2019-08-05 14 29 34" src="https://user-images.githubusercontent.com/49936253/62465957-75bcec80-b790-11e9-8b93-4e81789baac9.png"> <img width="132" alt="Skärmklipp 2019-08-05 13 28 14" src="https://user-images.githubusercontent.com/49936253/62465958-75bcec80-b790-11e9-8d16-c78dc4f9d7fe.png"> <img width="136" alt="Skärmklipp 2019-08-05 13 27 56" src="https://user-images.githubusercontent.com/49936253/62465959-75bcec80-b790-11e9-9159-af62de8fb5bc.png">

**Comment by recraft-ou** [comment]
1. Toppen med något att jämföra mot. Tack!

1. Aha, decimalerna anges efter ett komma- jag tror decimalpunkt vs decimalkomma var det som trasslade till detta, det jag hade förutsatte/förväntade sig nog en decimalpunkt.

1. Jag ska fixa återkopplings-länken, tack!

1. Toppen. Se #3 - jag har satt att en nattlig uppdatering sker automatiskt, om den trasslar ska senast fungerande data användas.

**Comment by recraft-ou** [comment]
Nu är den senaste importen gjord, det var något fel i sökvägen för det schemalagda kommandot jag använde så den hade inte kört i natt, men det är nu åtgärdat och importen gjord. 

Jag hittade ett fel där flaggor för "available" och "active" inte beaktades och gjorde en ändring samt testade för de pnr du skickade skärmdumparna för, här är resultatet:

För 17160 får jag nu 37 st för "Redan köpt", och 8 st är "oköpta" men finns i lager att köpa, vilket jag tror stämmer när jag räknar raderna i skärmdumpen. 

För 17158 får jag rätt antal för "Redan köpt" men 33 är "oköpta" och köpbara vilket är 1 mer än när jag räknar i den skärmdumpen, jag tror det beror på att prestashops API meddelar nr "1/14" är aktiv och tillgänglig medan jag ser att http://www.alternativ.nu/butik/%C3%A5ter/2014/%C3%A5ter-nr-114.html meddelar att den inte finns i lager, vilket är märkligt. 

För 9443 stämmer det jag får överens med skärmdumpen.

För 9442 för jag rätt antal för "Redan köpt" men än en gång en avvikelse på 1 för "Oköpta men köpbara", återigen pga nr "1/14" igen, verkar det som.

Prestashops API och datan där för Åter 1/14 kan kontrolleras på denna URL i browsern genom att ange de credentials som appen använder:

https://www.alternativ.nu/butik/api/products?output_format=JSON&display=[id,name,link_rewrite,active,available_for_order,description_short,id_default_image]&filter[active]=[0|1]

Sök sedan på "id":26 och se att den ska vara både active och available_for_order, jag undrar vad det är som strular här, så här ser JSON-datan ut för detta product id:

`{"id":26,"id_default_image":"270","active":"1","available_for_order":"1","link_rewrite":"åter-nr-114","name":"Åter nr 1\/14", ...etc ...}`

**Comment by recraft-ou** [comment]
Ändringen är upplagd och kan testas på https://alternativ.nu/artiklar och ang PS API:et så blir effekten för Åter 1/14 att man kan klicka Köp-länken men "inget händer". 

Kanske kan denna avvikelse lösas genom att sätta endera av "active" eller "available_for_order" till false i Prestashop? Skulle det fungera?

**Comment by TidningenAter** [comment]
Wow, härligt. Det verkar funka!
Ang 1/14 så var den aktiv men oköpbar pga att det inte fanns i lager, annars brukar jag inaktivera tidningar som är slut, vilket jag nu gjort även med 1/14. Så det inte spökar. 
Om det är bökigt att kolla köpstatus via Prestashop så kan jag inkludera det i tab-filerna jag exporterar?

**Comment by recraft-ou** [comment]
Det är bra, ändringen du gör i prestashop bör slå igenom direkt då API:et används vid varje förfrågan, medan .tab-filerna ju uppdateras mer sällan dvs nattligen (kl 02:30) och eftersom det ändå finns ett beroende på PS så tycker jag att vi lämnar det som det står just nu. Det blir mer up-to-date på det vised och att ha informationen från två källor varav en kan vara i osynk blir lite svårare att hantera.

När detta väl snurrar hyfsat stabilt med barnsjunkdomarna åtgärdade så tycker jag att vi funderar över vad man skulle vilja ändra på i dataflöde mm. Eventuellt finns det ett fält för lagersaldo som jag skulle ha frågat efter från PS och kolla om det sjunkit till noll. 

Jag stänger nu denna ticket då det verkar fungera som det ska.
