### ISSUE TITLE
Möjlighet för återkoppling 

### ISSUE THREAD

**Issue by recraft-ou** [alternativ-nu/retrosearch#19]
Lägg till länk för att lämna feedback via mail till feedback@alternativ.nu

**Comment by recraft-ou** [comment]
Finns nu i versionen på alternativ.nu/artiklar

**Comment by TidningenAter** [comment]
Såg Återkopplingslänken, den var snygg men du kan justera länken så det inte öppnas ett nytt fönster i webbläsaren och ta bort // efter mailto:

**Comment by recraft-ou** [comment]
Tackar, det gick lite fort där, jag ska fixa detta i nästa version jag lägger upp.

**Comment by recraft-ou** [comment]
Ska vara fixat och finns på https://alternativ.nu/artiklar
