### ISSUE TITLE
Gränssnittets layout

### ISSUE THREAD

**Issue by recraft-ou** [alternativ-nu/retrosearch#5]
Denna ticket kan användas för att fånga upp önskemål, begränsingar och tankar kring gränssnittet, exv högerspalt eller inte mm.

Gränssnittet är just nu inte definierat i HTML (vilket är möjligt) utan i filen ui.R

Följande visar hur man kan använda HTML istället om man vill frångå layouten som shinydashboard erbjuder "out of the box":

https://shiny.rstudio.com/articles/html-tags.html
https://shiny.rstudio.com/articles/html-ui.html

En jquery-komponent "datatable" används för publikationslistan vilket ger inbyggd sökfunktionalitet mm, dock ej stöd för "avskiljare" mellan sektioner - såvitt jag vet.

**Comment by TidningenAter** [comment]
Det tekniska är lite överkurs för mig, men vill du att jag listar idéer och önskemål om gränssnittet i denna tråd?
Har för mig att du sade att du inte var så haj på utseende själv, är det så att vi ska ta in någon annan till detta? När i processen är det i så fall aktuellt och känner du kanske någon lämplig?

**Comment by TidningenAter** [comment]
Ojdå, jag skapade just en massa issues som jag kanske borde lagt i denna tråd istället?

**Comment by TidningenAter** [comment]
Stänger denna och delar upp de olika önskemålen i egna issues
