### ISSUE TITLE
Vid filtrering hoppar innehållet till höger

### ISSUE THREAD

**Issue by TidningenAter** [alternativ-nu/retrosearch#7]
<img width="1042" alt="Skärmklipp 2019-05-27 14 18 26" src="https://user-images.githubusercontent.com/49936253/58422769-bbc04a80-8093-11e9-8379-70e22afd8728.png">

**Comment by recraft-ou** [comment]
Jag tror att jag lyckats fixa till just högerhoppandet i den version som nu är uppe. Ta gärna en titt och om du är nöjd kan du stänga ner denna issue.
