### ISSUE TITLE
Dölj Köpknapp om numret är slutsålt

### ISSUE THREAD

**Issue by TidningenAter** [alternativ-nu/retrosearch#9]

**Comment by recraft-ou** [comment]
Ja detta ska fixas.

**Comment by recraft-ou** [comment]
Jag tror att detta är fixat nu, lite beroende på vad som avses i denna issue, men ingen köpknapp visas just nu om det inte finns något i lager. Om du är nöjd kan vi stänga denna?

**Comment by TidningenAter** [comment]
Japp, det blev perfekt med köpknappen till höger. Men det är ju bra om Titeln på tidningen fortsätter finnas ovanför artiklarna.

**Comment by recraft-ou** [comment]
Jag föreslår att vi gör en ny issue för detta med Titeln ovanför artiklarna. Kanske även för att göra de där köplänkarna lite snyggare så att de ser ut som riktiga knappar? Så stänger vi denna, om du tycker att det verkar vettigt.

**Comment by TidningenAter** [comment]
Låter bra
